# アドオンの情報
ADDON_NAME = "My_Addon"
ADDON_VERSION = (1, 0)
BLENDER_VERSION = (4, 1, 0)

# カテゴリー定義
CATEGORY_PLAYER = "PLAYER"
CATEGORY_ENEMY = "ENEMY"
CATEGORY_BOX = "BOX"
CATEGORY_OTHER = "OTHER"

# コライダー関連の定数
COLLIDER_TYPE_NONE = "NONE"
COLLIDER_TYPE_AABB = "AABB"
COLLIDER_TYPE_OBB = "OBB"
COLLIDER_TYPE_SPHERE = "SPHERE"

COLLIDER_TYPES = [
    (COLLIDER_TYPE_NONE, "None", ""),
    (COLLIDER_TYPE_AABB, "AABB", "AABB"),
    (COLLIDER_TYPE_OBB, "OBB", "OBB"),
    (COLLIDER_TYPE_SPHERE, "Sphere", "Sphere"),
]

# ファイル名関連
DEFAULT_COLLIDER_FILENAME = "default_collider.json"

# プロパティのデフォルト値
DEFAULT_COLLIDER_CENTER = (0, 0, 0)
DEFAULT_COLLIDER_SIZE = (2, 2, 2)
DEFAULT_COLLIDER_RADIUS = 1.0
